# Generated by Django 5.0.9 on 2026-10-02 05:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commercial", "0002_seed_classes_e_tributos"),
        ("livestock", "0003_lot_origin_purchase_alter_lot_status"),
        ("organizations", "0003_season_uniq_current_season_per_company"),
        ("partners", "0001_initial"),
        (
            "properties",
            "0002_farm_business_unit_farm_city_farm_pasture_area_ha_and_more",
        ),
        ("purchases", "0002_purchase_payment_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("CONFIRMADA", "Confirmada"),
                            ("EXCLUIDA", "Excluída"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versão"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "delete_reason",
                    models.TextField(blank=True, verbose_name="Motivo da exclusão"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("date", models.DateField(verbose_name="Data do movimento")),
                (
                    "origin_property",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Propriedade de origem"
                    ),
                ),
                (
                    "origin_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cidade de origem"
                    ),
                ),
                (
                    "payment_days",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Prazo de pagamento (dias)"
                    ),
                ),
                (
                    "pickup_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da retirada"
                    ),
                ),
                (
                    "slaughter_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data prevista do abate"
                    ),
                ),
                (
                    "trucks",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Caminhões"
                    ),
                ),
                (
                    "distance_km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Distância (km)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aprovado em"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "commissioned",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commitments_as_commissioned",
                        to="partners.partner",
                        verbose_name="Comprador (comissionado)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Excluído por",
                    ),
                ),
                (
                    "destination_farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commitments",
                        to="properties.farm",
                        verbose_name="Fazenda de destino",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commitments",
                        to="organizations.season",
                        verbose_name="Safra",
                    ),
                ),
                (
                    "second_buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="partners.partner",
                        verbose_name="Comprador adicional",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commitments_as_seller",
                        to="partners.partner",
                        verbose_name="Produtor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compromisso",
                "verbose_name_plural": "Compromissos",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("REGRA", "Regra cadastrada"),
                            ("MANUAL", "Informada neste compromisso"),
                        ],
                        default="REGRA",
                        max_length=8,
                        verbose_name="Origem",
                    ),
                ),
                ("type", models.CharField(max_length=12, verbose_name="Tipo")),
                ("base", models.CharField(max_length=8, verbose_name="Base")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="Valor (% ou R$ por cabeça)",
                    ),
                ),
                (
                    "extra_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Comissão extra (R$)",
                    ),
                ),
                (
                    "snapshot_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Gravada em"),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="partners.partner",
                        verbose_name="Favorecido",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="commercial.commissionrule",
                        verbose_name="Regra de origem",
                    ),
                ),
                (
                    "commitment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission",
                        to="procurement.commitment",
                        verbose_name="Compromisso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comissão do compromisso",
                "verbose_name_plural": "Comissões dos compromissos",
            },
        ),
        migrations.CreateModel(
            name="CommitmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Retirada em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="Item")),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Código do produto"
                    ),
                ),
                (
                    "head_count",
                    models.PositiveIntegerField(verbose_name="Cabeças previstas"),
                ),
                (
                    "avg_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="Peso médio previsto (kg)",
                    ),
                ),
                (
                    "price_basis",
                    models.CharField(
                        choices=[
                            ("ARROBA", "@ de carcaça (por faixa)"),
                            ("CABECA", "Por cabeça"),
                        ],
                        default="ARROBA",
                        max_length=8,
                        verbose_name="Base do preço",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Preço por cabeça (R$)",
                    ),
                ),
                (
                    "price_band_1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Faixa 1 (R$/@)",
                    ),
                ),
                (
                    "price_band_2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Faixa 2 (R$/@)",
                    ),
                ),
                (
                    "price_band_3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Faixa 3 (R$/@)",
                    ),
                ),
                (
                    "price_band_4",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Faixa 4 (R$/@)",
                    ),
                ),
                (
                    "price_band_5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Faixa 5 (R$/@)",
                    ),
                ),
                (
                    "expected_arrobas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Média @ prevista por cabeça",
                    ),
                ),
                (
                    "expected_band",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Faixa esperada",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commitment_items",
                        to="livestock.animalcategory",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "commitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="procurement.commitment",
                        verbose_name="Compromisso",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vazio = a compra cria um lote novo.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="livestock.lot",
                        verbose_name="Lote existente",
                    ),
                ),
                (
                    "purchase",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commitment_item",
                        to="purchases.purchase",
                        verbose_name="Compra gerada",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Retirada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do compromisso",
                "verbose_name_plural": "Itens do compromisso",
                "ordering": ["commitment_id", "number"],
            },
        ),
        migrations.CreateModel(
            name="GradingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Retirada em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "band",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Faixa",
                    ),
                ),
                ("head_count", models.PositiveIntegerField(verbose_name="Cabeças")),
                (
                    "carcass_weight_kg",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Peso de carcaça (kg)",
                    ),
                ),
                (
                    "price_per_arroba",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Preço da @ (R$)"
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Desconto (%)",
                    ),
                ),
                (
                    "carcass_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="commercial.carcassclass",
                        verbose_name="Classificação",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gradings",
                        to="procurement.commitmentitem",
                        verbose_name="Item",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Retirada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha do romaneio",
                "verbose_name_plural": "Linhas do romaneio",
                "ordering": ["item_id", "carcass_class__display_order", "band", "id"],
            },
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("CONFIRMADA", "Confirmada"),
                            ("EXCLUIDA", "Excluída"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versão"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "delete_reason",
                    models.TextField(blank=True, verbose_name="Motivo da exclusão"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("date", models.DateField(verbose_name="Data do acerto")),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aprovado em"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "commitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="procurement.commitment",
                        verbose_name="Compromisso",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Excluído por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acerto",
                "verbose_name_plural": "Acertos",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FiscalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Retirada em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                ("number", models.CharField(max_length=20, verbose_name="Número")),
                (
                    "series",
                    models.CharField(blank=True, max_length=5, verbose_name="Série"),
                ),
                ("issue_date", models.DateField(verbose_name="Data de emissão")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Retirada por",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_notes",
                        to="procurement.settlement",
                        verbose_name="Acerto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota fiscal",
                "verbose_name_plural": "Notas fiscais",
                "ordering": ["settlement_id", "issue_date", "number"],
            },
        ),
        migrations.CreateModel(
            name="SettlementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Retirada em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Documento"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Observação"
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Retirada por",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="procurement.settlement",
                        verbose_name="Acerto",
                    ),
                ),
                (
                    "tax_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="commercial.taxtype",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha do acerto",
                "verbose_name_plural": "Linhas do acerto",
                "ordering": ["settlement_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("CONFIRMADA", "Confirmada"),
                            ("EXCLUIDA", "Excluída"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versão"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "delete_reason",
                    models.TextField(blank=True, verbose_name="Motivo da exclusão"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("pickup_date", models.DateField(verbose_name="Data da retirada")),
                (
                    "driver_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Motorista"
                    ),
                ),
                (
                    "vehicle_plate",
                    models.CharField(blank=True, max_length=10, verbose_name="Placa"),
                ),
                (
                    "distance_km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Distância (km)"
                    ),
                ),
                (
                    "freight_criterion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("POR_CABECA", "Por cabeça"),
                            ("POR_KM", "Por km rodado"),
                            ("POR_KG", "Por kg de origem"),
                            ("POR_VIAGEM", "Valor fechado da viagem"),
                        ],
                        max_length=12,
                        verbose_name="Critério do frete",
                    ),
                ),
                (
                    "freight_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="Tarifa (R$)",
                    ),
                ),
                (
                    "freight_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Frete realizado (R$)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="partners.partner",
                        verbose_name="Transportador",
                    ),
                ),
                (
                    "commitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="procurement.commitment",
                        verbose_name="Compromisso",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Excluído por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Viagem",
                "verbose_name_plural": "Viagens",
                "ordering": ["pickup_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="Receiving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("CONFIRMADA", "Confirmada"),
                            ("EXCLUIDA", "Excluída"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versão"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "delete_reason",
                    models.TextField(blank=True, verbose_name="Motivo da exclusão"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("date", models.DateField(verbose_name="Data do recebimento")),
                ("notes", models.TextField(blank=True, verbose_name="Ocorrências")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Excluído por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivings",
                        to="procurement.trip",
                        verbose_name="Viagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recebimento",
                "verbose_name_plural": "Recebimentos",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TripLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Retirada em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "planned_qty",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cabeças programadas"
                    ),
                ),
                (
                    "shipped_qty",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Cabeças embarcadas"
                    ),
                ),
                (
                    "origin_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Peso de origem (kg)",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loads",
                        to="procurement.commitmentitem",
                        verbose_name="Item",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Retirada por",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loads",
                        to="procurement.trip",
                        verbose_name="Viagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carga da viagem",
                "verbose_name_plural": "Cargas da viagem",
                "ordering": ["trip_id", "item__number"],
            },
        ),
        migrations.CreateModel(
            name="ReceivingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Retirada em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "received_qty",
                    models.PositiveIntegerField(verbose_name="Cabeças recebidas"),
                ),
                (
                    "received_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Peso recebido (kg)",
                    ),
                ),
                (
                    "occurrence",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ocorrência"
                    ),
                ),
                (
                    "received_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Só se for diferente da prevista.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="livestock.animalcategory",
                        verbose_name="Categoria recebida",
                    ),
                ),
                (
                    "receiving",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="procurement.receiving",
                        verbose_name="Recebimento",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Retirada por",
                    ),
                ),
                (
                    "load",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_lines",
                        to="procurement.tripload",
                        verbose_name="Carga",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha do recebimento",
                "verbose_name_plural": "Linhas do recebimento",
                "ordering": ["receiving_id", "load__item__number"],
            },
        ),
        migrations.AddIndex(
            model_name="commitment",
            index=models.Index(
                fields=["season", "date"], name="procurement_season__bc8973_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="commitment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("pickup_date__isnull", True),
                    ("slaughter_date__isnull", True),
                    ("slaughter_date__gte", models.F("pickup_date")),
                    _connector="OR",
                ),
                name="commitment_slaughter_after_pickup",
            ),
        ),
        migrations.AddConstraint(
            model_name="commission",
            constraint=models.CheckConstraint(
                check=models.Q(("value__gte", 0)), name="commission_value_not_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="commission",
            constraint=models.CheckConstraint(
                check=models.Q(("extra_amount__gte", 0)),
                name="commission_extra_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="commitmentitem",
            constraint=models.CheckConstraint(
                check=models.Q(("head_count__gt", 0)),
                name="commitmentitem_head_count_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="commitmentitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed_at__isnull", True)),
                fields=("commitment", "number"),
                name="uniq_commitmentitem_number_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="commitmentitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("expected_band__isnull", True),
                    models.Q(("expected_band__gte", 1), ("expected_band__lte", 5)),
                    _connector="OR",
                ),
                name="commitmentitem_expected_band_1_to_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradingline",
            constraint=models.CheckConstraint(
                check=models.Q(("band__gte", 1), ("band__lte", 5)),
                name="gradingline_band_1_to_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradingline",
            constraint=models.CheckConstraint(
                check=models.Q(("head_count__gt", 0)),
                name="gradingline_head_count_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradingline",
            constraint=models.CheckConstraint(
                check=models.Q(("carcass_weight_kg__gt", 0)),
                name="gradingline_weight_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradingline",
            constraint=models.CheckConstraint(
                check=models.Q(("price_per_arroba__gt", 0)),
                name="gradingline_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradingline",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("discount_percent__gte", 0), ("discount_percent__lte", 100)
                ),
                name="gradingline_discount_0_to_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "EXCLUIDA"), _negated=True),
                fields=("commitment",),
                name="uniq_settlement_per_commitment",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalnote",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gte", 0)),
                name="fiscalnote_amount_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalnote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed_at__isnull", True)),
                fields=("settlement", "number", "series"),
                name="uniq_fiscalnote_number_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementline",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="settlementline_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("freight_actual__isnull", True),
                    ("freight_actual__gte", 0),
                    _connector="OR",
                ),
                name="trip_freight_actual_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("freight_rate__isnull", True),
                    ("freight_rate__gte", 0),
                    _connector="OR",
                ),
                name="trip_freight_rate_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="receiving",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "EXCLUIDA"), _negated=True),
                fields=("trip",),
                name="uniq_receiving_per_trip",
            ),
        ),
        migrations.AddConstraint(
            model_name="tripload",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed_at__isnull", True)),
                fields=("trip", "item"),
                name="uniq_tripload_item_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="tripload",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("origin_weight_kg__isnull", True),
                    ("origin_weight_kg__gt", 0),
                    _connector="OR",
                ),
                name="tripload_origin_weight_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="receivingline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed_at__isnull", True)),
                fields=("receiving", "load"),
                name="uniq_receivingline_load_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="receivingline",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("received_weight_kg__isnull", True),
                    ("received_weight_kg__gt", 0),
                    _connector="OR",
                ),
                name="receivingline_weight_positive",
            ),
        ),
    ]
