# Generated by Django 5.0.9 on 2026-10-03 16:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0003_paymentcondition_taxtype_effect_and_more"),
        ("partners", "0001_initial"),
        ("procurement", "0002_recebimento_quebra_informada"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Descontos (R$)",
                    ),
                ),
                (
                    "abatement_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Adiantamentos e créditos (R$)",
                    ),
                ),
                (
                    "freight_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Frete (R$)",
                    ),
                ),
                (
                    "commission_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Comissão (R$)",
                    ),
                ),
                (
                    "tax_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Tributos e taxas (R$)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribuição do acerto por item",
                "verbose_name_plural": "Distribuições do acerto por item",
                "ordering": ["settlement_id", "item__number"],
            },
        ),
        migrations.AlterModelOptions(
            name="commission",
            options={
                "ordering": ["commitment_id", "position", "id"],
                "verbose_name": "Comissão do compromisso",
                "verbose_name_plural": "Comissões dos compromissos",
            },
        ),
        migrations.AddField(
            model_name="commission",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Vencimento"),
        ),
        migrations.AddField(
            model_name="commission",
            name="position",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Ordem"),
        ),
        migrations.AddField(
            model_name="commitment",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Encerrada em"
            ),
        ),
        migrations.AddField(
            model_name="commitment",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Encerrada por",
            ),
        ),
        migrations.AddField(
            model_name="commitment",
            name="closure_note",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Observação do encerramento"
            ),
        ),
        migrations.AddField(
            model_name="commitment",
            name="payment_condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="commercial.paymentcondition",
                verbose_name="Condição de pagamento",
            ),
        ),
        migrations.AddField(
            model_name="commitmentitem",
            name="entry_yield_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Rendimento estimado de entrada (%)",
            ),
        ),
        migrations.AddField(
            model_name="settlementline",
            name="base_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Base (R$)",
            ),
        ),
        migrations.AddField(
            model_name="settlementline",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Vencimento"),
        ),
        migrations.AddField(
            model_name="settlementline",
            name="payee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="partners.partner",
                verbose_name="Favorecido",
            ),
        ),
        migrations.AddField(
            model_name="settlementline",
            name="rate_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=7,
                null=True,
                verbose_name="Alíquota (%)",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="adf_number",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Número do ADF"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="freight_due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Vencimento do frete"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="vehicle",
            field=models.CharField(blank=True, max_length=100, verbose_name="Veículo"),
        ),
        migrations.AlterField(
            model_name="commission",
            name="base",
            field=models.CharField(default="BRUTO", max_length=8, verbose_name="Base"),
        ),
        migrations.AlterField(
            model_name="commission",
            name="commitment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commissions",
                to="procurement.commitment",
                verbose_name="Compromisso",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="payee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="partners.partner",
                verbose_name="Comprador",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="value",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=12,
                verbose_name="Valor (%, R$ por cabeça ou R$)",
            ),
        ),
        migrations.AddConstraint(
            model_name="commission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("payee__isnull", False)),
                fields=("commitment", "payee"),
                name="uniq_commission_buyer_per_commitment",
            ),
        ),
        migrations.AddField(
            model_name="settlementallocation",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="procurement.commitmentitem",
                verbose_name="Item",
            ),
        ),
        migrations.AddField(
            model_name="settlementallocation",
            name="settlement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="procurement.settlement",
                verbose_name="Acerto",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementallocation",
            constraint=models.UniqueConstraint(
                fields=("settlement", "item"), name="uniq_allocation_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementallocation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("discount_value__gte", 0),
                    ("abatement_value__gte", 0),
                    ("freight_value__gte", 0),
                    ("commission_value__gte", 0),
                    ("tax_value__gte", 0),
                ),
                name="allocation_not_negative",
            ),
        ),
    ]
