# Generated by Django 5.0.9 on 2026-10-01 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0002_lot'),
        ('organizations', '0003_season_uniq_current_season_per_company'),
        ('partners', '0001_initial'),
        ('properties', '0002_farm_business_unit_farm_city_farm_pasture_area_ha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIRMADA', 'Confirmada'), ('EXCLUIDA', 'Excluída')], default='RASCUNHO', max_length=20, verbose_name='Situação')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('delete_reason', models.TextField(blank=True, verbose_name='Motivo da exclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('date', models.DateField(verbose_name='Data da compra')),
                ('head_count', models.PositiveIntegerField(verbose_name='Cabeças')),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Peso total (kg)')),
                ('animal_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor dos animais (R$)')),
                ('freight_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Frete (R$)')),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Comissão (R$)')),
                ('tax_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Impostos (R$)')),
                ('partnership', models.CharField(blank=True, max_length=100, verbose_name='Parceria')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='livestock.animalcategory', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('destination_farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='properties.farm', verbose_name='Fazenda de destino')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='livestock.lot', verbose_name='Lote')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='organizations.season', verbose_name='Safra')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_to_us', to='partners.partner', verbose_name='Vendedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(check=models.Q(('head_count__gt', 0)), name='purchase_head_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(check=models.Q(('animal_value__gt', 0)), name='purchase_animal_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(check=models.Q(('freight_value__gte', 0), ('commission_value__gte', 0), ('tax_value__gte', 0)), name='purchase_accessories_not_negative'),
        ),
    ]
