# Generated by Django 5.0.9 on 2026-10-03 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0003_paymentcondition_taxtype_effect_and_more"),
        ("purchases", "0002_purchase_payment_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="entry_yield_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Rendimento estimado de entrada (%)",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="payment_condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="commercial.paymentcondition",
                verbose_name="Condição de pagamento",
            ),
        ),
    ]
