# Generated by Django 5.0.9 on 2026-10-02 05:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("livestock", "0003_lot_origin_purchase_alter_lot_status"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarcassClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Nome")),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "default_band",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Opcional. Só sugere a faixa no romaneio; quem escolhe é você.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Faixa sugerida",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Classificação de carcaça",
                "verbose_name_plural": "Classificações de carcaça",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CommissionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PERCENTUAL", "Percentual"),
                            ("POR_CABECA", "Valor por cabeça"),
                        ],
                        default="PERCENTUAL",
                        max_length=12,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "base",
                    models.CharField(
                        choices=[
                            ("BRUTO", "Valor bruto dos animais"),
                            ("LIQUIDO", "Valor líquido (sem frete e tributos)"),
                        ],
                        default="BRUTO",
                        max_length=8,
                        verbose_name="Base do percentual",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="Valor (% ou R$ por cabeça)",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Vale desde")),
                (
                    "valid_to",
                    models.DateField(blank=True, null=True, verbose_name="Vale até"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
            ],
            options={
                "verbose_name": "Regra de comissão",
                "verbose_name_plural": "Regras de comissão",
                "ordering": ["-valid_from", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TaxType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="Nome"),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("TRIBUTO", "Tributo"),
                            ("TAXA", "Taxa"),
                            ("DESCONTO", "Desconto"),
                            ("ADIANTAMENTO", "Adiantamento"),
                            ("CREDITO", "Crédito"),
                        ],
                        default="TAXA",
                        max_length=14,
                        verbose_name="Natureza",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Tipo de tributo, taxa ou desconto",
                "verbose_name_plural": "Tipos de tributo, taxa e desconto",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="carcassclass",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("default_band__isnull", True),
                    models.Q(("default_band__gte", 1), ("default_band__lte", 5)),
                    _connector="OR",
                ),
                name="carcassclass_band_1_to_5",
            ),
        ),
        migrations.AddField(
            model_name="commissionrule",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Vazio = vale para qualquer categoria.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commission_rules",
                to="livestock.animalcategory",
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="commissionrule",
            name="commissioned",
            field=models.ForeignKey(
                blank=True,
                help_text="Vazio = vale para qualquer comprador.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commission_rules",
                to="partners.partner",
                verbose_name="Comissionado",
            ),
        ),
        migrations.AddConstraint(
            model_name="commissionrule",
            constraint=models.CheckConstraint(
                check=models.Q(("value__gt", 0)), name="commissionrule_value_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="commissionrule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="commissionrule_valid_range",
            ),
        ),
    ]
