# Generated by Django 5.0.9 on 2026-10-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0002_seed_classes_e_tributos"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="Nome"),
                ),
                (
                    "days",
                    models.CharField(
                        default="0",
                        help_text="Dias depois da data da operação. Um número = à vista ou prazo único; vários separados por vírgula = parcelado (ex.: 30,60,90).",
                        max_length=60,
                        verbose_name="Dias",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
            ],
            options={
                "verbose_name": "Condição de pagamento",
                "verbose_name_plural": "Condições de pagamento",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="taxtype",
            name="effect",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CUSTO", "Soma ao custo de aquisição e gera título"),
                    ("DESCONTO_NO_ANIMAL", "Reduz o valor dos animais"),
                    ("ABATE_NO_LIQUIDO", "Reduz só o líquido a pagar ao vendedor"),
                ],
                help_text="Vazio = o padrão da natureza escolhida.",
                max_length=20,
                verbose_name="Efeito no acerto",
            ),
        ),
        migrations.AlterField(
            model_name="commissionrule",
            name="type",
            field=models.CharField(
                choices=[
                    ("PERCENTUAL", "Percentual"),
                    ("POR_CABECA", "Valor por cabeça"),
                    ("VALOR", "Valor informado (R$)"),
                ],
                default="PERCENTUAL",
                max_length=12,
                verbose_name="Tipo",
            ),
        ),
    ]
