# Generated by Django 5.0.9 on 2026-10-01 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
        ('livestock', '0002_lot'),
        ('organizations', '0003_season_uniq_current_season_per_company'),
        ('partners', '0001_initial'),
        ('properties', '0002_farm_business_unit_farm_city_farm_pasture_area_ha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='allocation_criterion',
            field=models.CharField(choices=[('POR_CABECA_DIA', 'Cabeça-dia'), ('POR_CABECA_SIMPLES', 'Cabeças no fim do período'), ('POR_ARROBA_PRODUZIDA', 'Arroba produzida'), ('MANUAL', 'Manual')], default='POR_CABECA_DIA', max_length=25, verbose_name='Critério de rateio'),
        ),
        migrations.CreateModel(
            name='CostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIRMADA', 'Confirmada'), ('EXCLUIDA', 'Excluída')], default='RASCUNHO', max_length=20, verbose_name='Situação')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('delete_reason', models.TextField(blank=True, verbose_name='Motivo da exclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('date', models.DateField(db_index=True, verbose_name='Data do fato')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor (R$)')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='costs.costcenter', verbose_name='Centro de custo')),
                ('cost_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='costs.costclass', verbose_name='Classe')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_entries', to='properties.farm', verbose_name='Fazenda')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_entries', to='livestock.lot', verbose_name='Lote')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.partner', verbose_name='Pagador')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_entries', to='organizations.season', verbose_name='Safra')),
            ],
            options={
                'verbose_name': 'Lançamento de custo',
                'verbose_name_plural': 'Lançamentos de custo',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
