# Generated by Django 5.0.9 on 2026-10-01 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_costcenter_allocation_criterion_costentry'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costentry',
            name='source_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_entries', to='purchases.purchase', verbose_name='Compra de origem'),
        ),
        migrations.AddField(
            model_name='costentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AddIndex(
            model_name='costentry',
            index=models.Index(fields=['farm', 'season'], name='costs_coste_farm_id_e7b857_idx'),
        ),
        migrations.AddIndex(
            model_name='costentry',
            index=models.Index(fields=['cost_center', 'season'], name='costs_coste_cost_ce_38876a_idx'),
        ),
        migrations.AddConstraint(
            model_name='costentry',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='costentry_amount_positive'),
        ),
    ]
