# Generated by Django 5.0.9 on 2026-10-04 05:12

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently, TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costs", "0005_centro_de_custo_frete"),
        ("livestock", "0004_lot_regime"),
        ("organizations", "0003_season_uniq_current_season_per_company"),
        ("partners", "0002_indices_de_desempenho"),
        (
            "properties",
            "0002_farm_business_unit_farm_city_farm_pasture_area_ha_and_more",
        ),
        ("purchases", "0003_purchase_entry_yield_percent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # `CREATE INDEX CONCURRENTLY` não trava a escrita enquanto o índice é
    # construído (importa em produção, com a tabela em uso). Exige fora de
    # transação.
    atomic = False

    operations = [
        TrigramExtension(),
        AddIndexConcurrently(
            model_name="costentry",
            index=models.Index(
                condition=models.Q(("lot__isnull", True), ("status", "CONFIRMADA")),
                fields=["farm", "date"],
                name="costentry_indireto_farm_date",
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS costentry_description_trgm "
                "ON costs_costentry USING gin (UPPER(description) gin_trgm_ops)"
            ),
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS costentry_description_trgm",
        ),
    ]
