# Generated by Django 5.0.9 on 2026-10-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=60, unique=True, verbose_name="Nome"),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Macho"), ("F", "Fêmea"), ("-", "—")],
                        default="-",
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "age_order",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Ordem etária"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Ordem de exibição"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Categoria animal",
                "verbose_name_plural": "Categorias animais",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=60, unique=True, verbose_name="Nome"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Raça",
                "verbose_name_plural": "Raças",
                "ordering": ["name"],
            },
        ),
    ]
