# Generated by Django 5.0.9 on 2026-10-01 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
        ('livestock', '0001_initial'),
        ('organizations', '0003_season_uniq_current_season_per_company'),
        ('partners', '0001_initial'),
        ('properties', '0002_farm_business_unit_farm_city_farm_pasture_area_ha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('entry_date', models.DateField(verbose_name='Data de entrada')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='Data de saída')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ENCERRADO', 'Encerrado')], default='ABERTO', max_length=10, verbose_name='Situação')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='livestock.breed', verbose_name='Raça')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='costs.costcenter', verbose_name='Centro de custo')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='properties.farm', verbose_name='Fazenda')),
                ('origin_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.partner', verbose_name='Parceiro de origem')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='organizations.season', verbose_name='Safra')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-entry_date', 'code'],
                'indexes': [models.Index(fields=['farm', 'status'], name='livestock_l_farm_id_020a26_idx')],
            },
        ),
    ]
