# Generated by Django 5.0.9 on 2026-10-01 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_lot'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='origin_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_lots', to='purchases.purchase', verbose_name='Compra de origem'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ENCERRADO', 'Encerrado'), ('EXCLUIDO', 'Excluído')], default='ABERTO', max_length=10, verbose_name='Situação'),
        ),
    ]
