# Generated by Django 5.0.9 on 2026-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestock", "0003_lot_origin_purchase_alter_lot_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="regime",
            field=models.CharField(
                choices=[("PASTO", "Pasto"), ("CONFINAMENTO", "Confinamento")],
                default="PASTO",
                max_length=14,
                verbose_name="Regime",
            ),
        ),
    ]
