# Generated by Django 5.0.9 on 2026-10-03 00:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Exportação",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Na fila"),
                            ("PROCESSANDO", "Processando"),
                            ("PRONTO", "Pronta"),
                            ("ERRO", "Com erro"),
                            ("CANCELADO", "Cancelada"),
                            ("EXPIRADO", "Arquivo removido"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=12,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "params",
                    models.JSONField(blank=True, default=dict, verbose_name="Pedido"),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=list, verbose_name="Filtros"),
                ),
                (
                    "items",
                    models.JSONField(blank=True, default=list, verbose_name="Itens"),
                ),
                (
                    "stage",
                    models.CharField(blank=True, max_length=200, verbose_name="Etapa"),
                ),
                (
                    "work_total",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Trabalho a fazer"
                    ),
                ),
                (
                    "work_done",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Trabalho feito"
                    ),
                ),
                (
                    "cancel_requested",
                    models.BooleanField(
                        default=False, verbose_name="Cancelamento pedido"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="exports/%Y/%m/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Nome para baixar"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo do arquivo"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="SHA-256 do arquivo"
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Tamanho (bytes)"
                    ),
                ),
                (
                    "warnings",
                    models.JSONField(blank=True, default=list, verbose_name="Avisos"),
                ),
                ("error", models.TextField(blank=True, verbose_name="Motivo da falha")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Pedida em"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Começou em"
                    ),
                ),
                (
                    "heartbeat_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último sinal"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluída em"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Arquivo disponível até"
                    ),
                ),
                (
                    "file_removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Arquivo removido em"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pedida por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exportação",
                "verbose_name_plural": "Exportações",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["requested_by", "-created_at"],
                        name="exports_exp_request_7f1073_idx",
                    )
                ],
            },
        ),
    ]
