# Generated by Django 5.0.9 on 2026-10-01 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Quando"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Criou"),
                            ("UPDATE", "Alterou"),
                            ("DELETE", "Excluiu"),
                            ("RESTORE", "Restaurou"),
                            ("CONFIRM", "Confirmou"),
                            ("APPROVE", "Aprovou"),
                            ("LOGIN", "Entrou"),
                            ("LOGIN_FAILED", "Falha de login"),
                            ("LOGOUT", "Saiu"),
                            ("EXPORT", "Exportou"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=100, verbose_name="Tipo de entidade"),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ID da entidade"
                    ),
                ),
                (
                    "before",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Estado anterior"
                    ),
                ),
                (
                    "after",
                    models.JSONField(blank=True, null=True, verbose_name="Estado novo"),
                ),
                (
                    "changed_fields",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Campos alterados"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Motivo")),
                (
                    "cascade_root",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Raiz da cascata",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=400, verbose_name="User-Agent"
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="ID da requisição",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Quem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de auditoria",
                "verbose_name_plural": "Eventos de auditoria",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__0bff9a_idx",
                    ),
                    models.Index(
                        fields=["actor", "timestamp"],
                        name="audit_audit_actor_i_573746_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OperationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Quando"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=100, verbose_name="Tipo de entidade"),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ID da entidade"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "previous_status",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Status anterior"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Status novo"
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Documento"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Quem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de operação",
                "verbose_name_plural": "Eventos de operação",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_opera_entity__b7e475_idx",
                    )
                ],
            },
        ),
    ]
