# Generated by Django 5.0.9 on 2026-10-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditevent_immutable_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Criou'), ('UPDATE', 'Alterou'), ('DELETE', 'Excluiu'), ('RESTORE', 'Restaurou'), ('CONFIRM', 'Confirmou'), ('APPROVE', 'Aprovou'), ('LOGIN', 'Entrou'), ('LOGIN_FAILED', 'Falha de login'), ('LOGOUT', 'Saiu'), ('EXPORT', 'Exportou'), ('IMPORT', 'Importou'), ('CANCEL', 'Cancelou')], max_length=20, verbose_name='Ação'),
        ),
    ]
