# Generated by Django 5.0.9 on 2026-10-02 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_season_uniq_current_season_per_company"),
        ("partners", "0001_initial"),
        (
            "properties",
            "0002_farm_business_unit_farm_city_farm_pasture_area_ha_and_more",
        ),
        ("purchases", "0002_purchase_payment_days"),
        ("sales", "0002_sale_payment_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("CONFIRMADA", "Confirmada"),
                            ("EXCLUIDA", "Excluída"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versão"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "delete_reason",
                    models.TextField(blank=True, verbose_name="Motivo da exclusão"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("PAGAR", "A pagar"), ("RECEBER", "A receber")],
                        default="PAGAR",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("ANIMAIS", "Animais"),
                            ("FRETE", "Frete"),
                            ("COMISSAO", "Comissão"),
                            ("IMPOSTOS", "Impostos"),
                            ("VENDA", "Venda"),
                            ("OUTRO", "Outro"),
                        ],
                        default="OUTRO",
                        max_length=10,
                        verbose_name="Origem da obrigação",
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        blank=True,
                        help_text="Nota fiscal, duplicata, contrato…",
                        max_length=60,
                        verbose_name="Documento",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Emissão")),
                ("due_date", models.DateField(verbose_name="Vencimento")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("A_PAGAR", "A pagar"),
                            ("PROGRAMADO", "Programado"),
                            ("APROVADO", "Aprovado"),
                            ("PARCIAL", "Pago em parte"),
                            ("PAGO", "Pago"),
                        ],
                        default="A_PAGAR",
                        max_length=12,
                        verbose_name="Situação do pagamento",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Pagamento programado para"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aprovado em"
                    ),
                ),
                (
                    "voided_with_origin",
                    models.BooleanField(
                        default=False, verbose_name="Desfeito com a origem"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="partners.bankaccount",
                        verbose_name="Conta bancária",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Excluído por",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="properties.farm",
                        verbose_name="Fazenda",
                    ),
                ),
                (
                    "origin_purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="purchases.purchase",
                        verbose_name="Compra de origem",
                    ),
                ),
                (
                    "origin_sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="sales.sale",
                        verbose_name="Venda de origem",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="partners.partner",
                        verbose_name="Favorecido",
                    ),
                ),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Programado por",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="organizations.season",
                        verbose_name="Safra",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Título",
                "verbose_name_plural": "Títulos",
                "ordering": ["due_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("CONFIRMADA", "Confirmada"),
                            ("EXCLUIDA", "Excluída"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versão"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "delete_reason",
                    models.TextField(blank=True, verbose_name="Motivo da exclusão"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("date", models.DateField(verbose_name="Data do pagamento")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("PIX", "Pix"),
                            ("TED", "TED / transferência"),
                            ("BOLETO", "Boleto"),
                            ("CHEQUE", "Cheque"),
                            ("DINHEIRO", "Dinheiro"),
                            ("OUTRO", "Outro"),
                        ],
                        default="PIX",
                        max_length=10,
                        verbose_name="Forma",
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        help_text="Comprovante: nº da TED, ID do Pix, nº do cheque…",
                        max_length=60,
                        verbose_name="Documento de pagamento",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Excluído por",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.invoice",
                        verbose_name="Título",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baixa",
                "verbose_name_plural": "Baixas",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["farm", "season"], name="finance_inv_farm_id_b33b51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date", "payment_status"],
                name="finance_inv_due_dat_10375c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="invoice_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                check=models.Q(("due_date__gte", models.F("issue_date"))),
                name="invoice_due_after_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("origin_purchase__isnull", True),
                    ("origin_sale__isnull", True),
                    _connector="OR",
                ),
                name="invoice_single_origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origin_purchase__isnull", False)),
                fields=("origin_purchase", "component"),
                name="uniq_invoice_purchase_component",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origin_sale__isnull", False)),
                fields=("origin_sale", "component"),
                name="uniq_invoice_sale_component",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["date"], name="finance_pay_date_091c4c_idx"),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                check=models.Q(("document", ""), _negated=True),
                name="payment_document_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "EXCLUIDA"), _negated=True),
                fields=("invoice", "document"),
                name="uniq_payment_invoice_document",
            ),
        ),
    ]
