# Generated by Django 5.0.9 on 2026-10-03 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("organizations", "0003_season_uniq_current_season_per_company"),
        ("partners", "0001_initial"),
        ("procurement", "0002_recebimento_quebra_informada"),
        (
            "properties",
            "0002_farm_business_unit_farm_city_farm_pasture_area_ha_and_more",
        ),
        ("purchases", "0003_purchase_entry_yield_percent_and_more"),
        ("sales", "0003_sale_payment_condition_sale_reported_yield_percent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoice",
            name="invoice_single_origin",
        ),
        migrations.RemoveConstraint(
            model_name="invoice",
            name="uniq_invoice_purchase_component",
        ),
        migrations.RemoveConstraint(
            model_name="invoice",
            name="uniq_invoice_sale_component",
        ),
        migrations.AddField(
            model_name="invoice",
            name="origin_settlement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="procurement.settlement",
                verbose_name="Acerto de origem",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="ref",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Referência"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("origin_purchase__isnull", True), ("origin_sale__isnull", True)
                    ),
                    models.Q(
                        ("origin_purchase__isnull", True),
                        ("origin_settlement__isnull", True),
                    ),
                    models.Q(
                        ("origin_sale__isnull", True),
                        ("origin_settlement__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="invoice_single_origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origin_purchase__isnull", False)),
                fields=("origin_purchase", "component", "ref"),
                name="uniq_invoice_purchase_component",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origin_sale__isnull", False)),
                fields=("origin_sale", "component", "ref"),
                name="uniq_invoice_sale_component",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origin_settlement__isnull", False)),
                fields=("origin_settlement", "component", "ref"),
                name="uniq_invoice_settlement_component",
            ),
        ),
    ]
