# Generated by Django 5.0.9 on 2026-10-03 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_season_uniq_current_season_per_company"),
        (
            "properties",
            "0002_farm_business_unit_farm_city_farm_pasture_area_ha_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BreedingCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("CONFIRMADA", "Confirmada"),
                            ("EXCLUIDA", "Excluída"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versão"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "delete_reason",
                    models.TextField(blank=True, verbose_name="Motivo da exclusão"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                (
                    "breeding_months",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Tempo de estação (meses)"
                    ),
                ),
                (
                    "females_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de fêmeas no rebanho"
                    ),
                ),
                (
                    "females_over_18m",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Fêmeas acima de 18 meses"
                    ),
                ),
                (
                    "heifers_exposed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Novilhas em monta"
                    ),
                ),
                (
                    "heifers_pregnant",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Novilhas prenhes"
                    ),
                ),
                (
                    "challenge_heifers_exposed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Novilhas desafio em monta"
                    ),
                ),
                (
                    "challenge_heifers_pregnant",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Novilhas desafio prenhes"
                    ),
                ),
                (
                    "primiparous_exposed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Primíparas em monta"
                    ),
                ),
                (
                    "primiparous_pregnant",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Primíparas prenhes"
                    ),
                ),
                (
                    "cows_exposed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Vacas em monta"
                    ),
                ),
                (
                    "cows_pregnant",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Vacas prenhes"
                    ),
                ),
                (
                    "inseminated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Fêmeas inseminadas (IA/IATF)"
                    ),
                ),
                (
                    "pregnant_by_ai",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Prenhes por IA/IATF"
                    ),
                ),
                (
                    "pregnant_by_bull",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Prenhes por touro"
                    ),
                ),
                (
                    "weaned_calves",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Bezerros desmamados"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Excluído por",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="breeding_cycles",
                        to="properties.farm",
                        verbose_name="Fazenda",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="breeding_cycles",
                        to="organizations.season",
                        verbose_name="Safra de nascimento",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciclo reprodutivo",
                "verbose_name_plural": "Ciclos reprodutivos",
                "ordering": ["-season__start_date", "farm__name", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="breedingcycle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "EXCLUIDA"), _negated=True),
                fields=("farm", "season"),
                name="uniq_breeding_cycle_farm_season",
            ),
        ),
        migrations.AddConstraint(
            model_name="breedingcycle",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("heifers_pregnant__lte", models.F("heifers_exposed")),
                    (
                        "challenge_heifers_pregnant__lte",
                        models.F("challenge_heifers_exposed"),
                    ),
                    ("primiparous_pregnant__lte", models.F("primiparous_exposed")),
                    ("cows_pregnant__lte", models.F("cows_exposed")),
                ),
                name="breeding_pregnant_within_exposed",
            ),
        ),
        migrations.AddConstraint(
            model_name="breedingcycle",
            constraint=models.CheckConstraint(
                check=models.Q(("pregnant_by_ai__lte", models.F("inseminated"))),
                name="breeding_ai_pregnant_within_inseminated",
            ),
        ),
    ]
