# Generated by Django 5.0.9 on 2026-10-01 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="farms",
                to="organizations.businessunit",
                verbose_name="Unidade",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AddField(
            model_name="farm",
            name="pasture_area_ha",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Área de pastagem (ha)",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="state",
            field=models.CharField(blank=True, max_length=2, verbose_name="UF"),
        ),
        migrations.AddField(
            model_name="farm",
            name="total_area_ha",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Área total (ha)",
            ),
        ),
        migrations.CreateModel(
            name="Paddock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "area_ha",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Área (ha)",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PASTAGEM", "Pastagem"),
                            ("SILAGEM", "Silagem"),
                            ("BENFEITORIA", "Benfeitoria"),
                            ("RESERVA_APP", "Reserva / APP"),
                            ("ARRENDAMENTO", "Arrendamento"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "capacity_ua",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Capacidade (UA)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paddocks",
                        to="properties.farm",
                        verbose_name="Fazenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área / Pasto",
                "verbose_name_plural": "Áreas / Pastos",
                "ordering": ["farm__name", "name"],
            },
        ),
    ]
