# Generated by Django 5.0.9 on 2026-10-02 15:18

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_totp_e_recovery"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="Nome completo"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        max_length=1000,
                        verbose_name="Quem é e por que precisa de acesso",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADA", "Aprovada"),
                            ("RECUSADA", "Recusada"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=10,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Solicitado em"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Decidido em"
                    ),
                ),
                (
                    "decision_reason",
                    models.TextField(blank=True, verbose_name="Motivo da decisão"),
                ),
            ],
            options={
                "verbose_name": "Solicitação de acesso",
                "verbose_name_plural": "Solicitações de acesso",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Excluído em"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False, verbose_name="Deve trocar a senha"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(
                    ("deleted_at__isnull", True), models.Q(("email", ""), _negated=True)
                ),
                name="uniq_user_email_ci",
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Decidido por",
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="access_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Conta criada",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrequest",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("status", "PENDENTE")),
                name="uniq_pending_access_request_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("decided_at__isnull", True), ("status", "PENDENTE")),
                    models.Q(
                        models.Q(("status", "PENDENTE"), _negated=True),
                        ("decided_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="access_request_decision_matches_status",
            ),
        ),
    ]
