# Generated by Django 5.0.9 on 2026-10-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_usuarios_gestao_e_solicitacoes"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de nascimento"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(blank=True, max_length=11, verbose_name="CPF"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                models.F("cpf"),
                condition=models.Q(
                    ("deleted_at__isnull", True), models.Q(("cpf", ""), _negated=True)
                ),
                name="uniq_user_cpf",
            ),
        ),
    ]
