# Generated by Django 5.0.9 on 2026-10-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_perfil"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="two_factor_reminder_until",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Lembrete do segundo fator adiado até",
            ),
        ),
    ]
