# Generated by Django 5.0.9 on 2026-10-03 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_lembrete_do_segundo_fator"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Hash do token"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Navegador"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=400, verbose_name="User-agent"
                    ),
                ),
                (
                    "created_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP ao confiar"
                    ),
                ),
                (
                    "last_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Último IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Confiado em"),
                ),
                ("last_used_at", models.DateTimeField(verbose_name="Último uso")),
                ("expires_at", models.DateTimeField(verbose_name="Vale até")),
                (
                    "absolute_expires_at",
                    models.DateTimeField(verbose_name="Teto de validade"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revogado em"
                    ),
                ),
                (
                    "revoked_reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Motivo da revogação"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo confiável",
                "verbose_name_plural": "Dispositivos confiáveis",
                "ordering": ["-last_used_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "revoked_at"], name="trusted_user_rev_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="trusteddevice",
            constraint=models.CheckConstraint(
                check=models.Q(("expires_at__lte", models.F("absolute_expires_at"))),
                name="trusted_device_expiry_within_cap",
            ),
        ),
    ]
