# Generated by Django 5.0.9 on 2026-10-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_dispositivo_confiavel"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("light", "Claro"), ("dark", "Escuro")],
                default="light",
                max_length=5,
                verbose_name="Tema da interface",
            ),
        ),
    ]
