# Generated by Django 5.0.9 on 2026-10-03 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "properties",
            "0002_farm_business_unit_farm_city_farm_pasture_area_ha_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CURRAL", "Curral"),
                            ("COCHO", "Cocho"),
                            ("BEBEDOURO", "Bebedouro"),
                            ("CERCA", "Cerca"),
                            ("BARRACAO", "Barracão / galpão"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=12,
                        verbose_name="Tipo",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Identificação")),
                (
                    "area_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Área (m²)",
                    ),
                ),
                (
                    "trough_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cocho (m)",
                    ),
                ),
                (
                    "waterers",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Bebedouros"
                    ),
                ),
                (
                    "animals",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantos animais usam esta estrutura — base das razões abaixo.",
                        null=True,
                        verbose_name="Animais atendidos",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="structures",
                        to="properties.farm",
                        verbose_name="Fazenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estrutura da fazenda",
                "verbose_name_plural": "Estruturas da fazenda",
                "ordering": ["farm__name", "kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Máquina")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TRATOR", "Trator"),
                            ("IMPLEMENTO", "Implemento"),
                            ("CAMINHAO", "Caminhão"),
                            ("UTILITARIO", "Utilitário / caminhonete"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=12,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "new_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Valor da máquina nova (R$)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="machines",
                        to="properties.farm",
                        verbose_name="Fazenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Máquina",
                "verbose_name_plural": "Máquinas",
                "ordering": ["farm__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="MachineLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("CONFIRMADA", "Confirmada"),
                            ("EXCLUIDA", "Excluída"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versão"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "delete_reason",
                    models.TextField(blank=True, verbose_name="Motivo da exclusão"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Horas trabalhadas"
                    ),
                ),
                (
                    "fuel_liters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Combustível (litros)",
                    ),
                ),
                (
                    "fuel_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Combustível (R$)",
                    ),
                ),
                (
                    "maintenance_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Manutenção (R$)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Excluído por",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="infrastructure.machine",
                        verbose_name="Máquina",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uso da máquina",
                "verbose_name_plural": "Usos das máquinas",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="farmstructure",
            constraint=models.UniqueConstraint(
                fields=("farm", "kind", "name"), name="uniq_structure_farm_kind_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="machine",
            constraint=models.UniqueConstraint(
                fields=("farm", "name"), name="uniq_machine_farm_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="machinelog",
            constraint=models.CheckConstraint(
                check=models.Q(("hours__gt", 0)), name="machinelog_hours_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="machinelog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("fuel_liters__isnull", True),
                        ("fuel_liters__gte", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("fuel_cost__isnull", True),
                        ("fuel_cost__gte", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("maintenance_cost__isnull", True),
                        ("maintenance_cost__gte", 0),
                        _connector="OR",
                    ),
                ),
                name="machinelog_not_negative",
            ),
        ),
    ]
