# Generated by Django 5.0.9 on 2026-10-01 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='Razão social')),
                ('trade_name', models.CharField(blank=True, max_length=150, verbose_name='Nome fantasia')),
                ('document', models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['document'], name='partners_pa_documen_65965e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(blank=True, max_length=10, verbose_name='Código do banco')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('branch', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('account', models.CharField(blank=True, max_length=30, verbose_name='Conta')),
                ('account_type', models.CharField(choices=[('CORRENTE', 'Conta corrente'), ('POUPANCA', 'Conta poupança')], default='CORRENTE', max_length=10, verbose_name='Tipo de conta')),
                ('pix_key', models.CharField(blank=True, max_length=140, verbose_name='Chave Pix')),
                ('is_default', models.BooleanField(default=False, verbose_name='Conta padrão')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='partners.partner', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Conta bancária',
                'verbose_name_plural': 'Contas bancárias',
            },
        ),
        migrations.CreateModel(
            name='PartnerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRODUTOR', 'Produtor'), ('FORNECEDOR', 'Fornecedor'), ('COMPRADOR', 'Comprador'), ('FRIGORIFICO', 'Frigorífico'), ('TRANSPORTADOR', 'Transportador'), ('MOTORISTA', 'Motorista'), ('COMISSIONADO', 'Comissionado'), ('FAVORECIDO', 'Favorecido'), ('PECUARISTA', 'Pecuarista')], max_length=20, verbose_name='Papel')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='partners.partner', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Papel do parceiro',
                'verbose_name_plural': 'Papéis do parceiro',
            },
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('partner',), name='uniq_default_bank_account_per_partner'),
        ),
        migrations.AddConstraint(
            model_name='partnerrole',
            constraint=models.UniqueConstraint(fields=('partner', 'role'), name='uniq_partner_role'),
        ),
    ]
