# Generated by Django 5.0.9 on 2026-10-02 01:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Documento",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("RELATORIO", "Relatório")],
                        default="RELATORIO",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=40, verbose_name="Tipo de entidade"),
                ),
                (
                    "entity_id",
                    models.CharField(
                        max_length=80, verbose_name="Identificador da entidade"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "template_version",
                    models.CharField(max_length=40, verbose_name="Versão do template"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Gerando"),
                            ("PRONTO", "Pronto"),
                            ("ERRO", "Com erro"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=10,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Parâmetros"
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Filtros impressos"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="documents/%Y/%m/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="SHA-256 do arquivo"
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Tamanho (bytes)"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Motivo da falha")),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Pedido em"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gerado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento gerado",
                "verbose_name_plural": "Documentos gerados",
                "ordering": ["-generated_at", "-id"],
            },
        ),
    ]
