# Generated by Django 5.0.9 on 2026-10-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generateddocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("RELATORIO", "Relatório"),
                    ("CONTRATO", "Contrato de compra"),
                ],
                default="RELATORIO",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
