# Generated by Django 5.0.9 on 2026-10-01 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0002_lot'),
        ('organizations', '0003_season_uniq_current_season_per_company'),
        ('partners', '0001_initial'),
        ('properties', '0002_farm_business_unit_farm_city_farm_pasture_area_ha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HerdMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIRMADA', 'Confirmada'), ('EXCLUIDA', 'Excluída')], default='RASCUNHO', max_length=20, verbose_name='Situação')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('delete_reason', models.TextField(blank=True, verbose_name='Motivo da exclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('date', models.DateField(verbose_name='Data do fato')),
                ('type', models.CharField(choices=[('SALDO_INICIAL', 'Saldo inicial'), ('COMPRA', 'Compra'), ('NASCIMENTO', 'Nascimento'), ('TRANSFERENCIA', 'Transferência'), ('EVOLUCAO', 'Evolução'), ('RECLASSIFICACAO', 'Reclassificação'), ('ABATE', 'Abate'), ('VENDA', 'Venda'), ('MORTE', 'Morte'), ('CONSUMO_DOACAO', 'Consumo / doação'), ('AJUSTE_INVENTARIO', 'Ajuste de inventário')], max_length=20, verbose_name='Tipo')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Peso total (kg)')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('notes', models.TextField(blank=True, verbose_name='Observação')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('destination_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='livestock.animalcategory', verbose_name='Categoria de destino')),
                ('destination_farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='properties.farm', verbose_name='Fazenda de destino')),
                ('destination_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='livestock.lot', verbose_name='Lote de destino')),
                ('origin_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='livestock.animalcategory', verbose_name='Categoria de origem')),
                ('origin_farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='properties.farm', verbose_name='Fazenda de origem')),
                ('origin_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='livestock.lot', verbose_name='Lote de origem')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.partner', verbose_name='Parceiro')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='organizations.season', verbose_name='Safra')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HerdLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Data do fato')),
                ('quantity', models.IntegerField(verbose_name='Quantidade (com sinal)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Peso (kg, com sinal)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='livestock.animalcategory', verbose_name='Categoria')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='properties.farm', verbose_name='Fazenda')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='livestock.lot', verbose_name='Lote')),
                ('reverses_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='herd.herdledgerentry', verbose_name='Reverte a linha')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='organizations.season', verbose_name='Safra')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='herd.herdmovement', verbose_name='Movimentação')),
            ],
            options={
                'verbose_name': 'Linha do razão do rebanho',
                'verbose_name_plural': 'Linhas do razão do rebanho',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='herdmovement',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='herdmovement_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='herdledgerentry',
            index=models.Index(fields=['farm', 'category', 'date'], name='herd_herdle_farm_id_a61aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='herdledgerentry',
            index=models.Index(fields=['lot', 'date'], name='herd_herdle_lot_id_189d68_idx'),
        ),
        migrations.AddIndex(
            model_name='herdledgerentry',
            index=models.Index(fields=['season'], name='herd_herdle_season__b0bbea_idx'),
        ),
        migrations.AddConstraint(
            model_name='herdledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('quantity', 0), _negated=True), name='herdledgerentry_quantity_not_zero'),
        ),
    ]
