# Generated by Django 5.0.9 on 2026-10-01 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herd', '0002_herd_invariantes_banco'),
        ('livestock', '0002_lot'),
        ('properties', '0002_farm_business_unit_farm_city_farm_pasture_area_ha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weighing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIRMADA', 'Confirmada'), ('EXCLUIDA', 'Excluída')], default='RASCUNHO', max_length=20, verbose_name='Situação')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('delete_reason', models.TextField(blank=True, verbose_name='Motivo da exclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('date', models.DateField(verbose_name='Data')),
                ('reason', models.CharField(choices=[('CONFERENCIA', 'Conferência'), ('COMPRA', 'Compra'), ('ABATE', 'Abate'), ('VACINA', 'Vacina'), ('VENDA', 'Venda')], max_length=20, verbose_name='Motivo')),
                ('head_count', models.PositiveIntegerField(verbose_name='Cabeças pesadas')),
                ('total_weight_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Peso total (kg)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weighings', to='properties.farm', verbose_name='Fazenda')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weighings', to='livestock.lot', verbose_name='Lote')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Pesagem',
                'verbose_name_plural': 'Pesagens',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WeighingAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_tag', models.CharField(blank=True, max_length=30, verbose_name='Brinco')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Peso (kg)')),
                ('weighing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='herd.weighing', verbose_name='Pesagem')),
            ],
            options={
                'verbose_name': 'Pesagem individual',
                'verbose_name_plural': 'Pesagens individuais',
            },
        ),
        migrations.AddConstraint(
            model_name='weighing',
            constraint=models.CheckConstraint(check=models.Q(('head_count__gt', 0)), name='weighing_head_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='weighing',
            constraint=models.CheckConstraint(check=models.Q(('total_weight_kg__gt', 0)), name='weighing_total_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='weighinganimal',
            constraint=models.CheckConstraint(check=models.Q(('weight_kg__gt', 0)), name='weighinganimal_weight_positive'),
        ),
    ]
