# Generated by Django 5.0.9 on 2026-10-01 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herd', '0003_weighing_weighinganimal_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herdmovement',
            name='origin_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='purchases.purchase', verbose_name='Compra de origem'),
        ),
    ]
