# Generated by Django 5.0.9 on 2026-10-02 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("herd", "0004_herdmovement_origin_purchase"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="herdmovement",
            name="origin_sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="sales.sale",
                verbose_name="Venda de origem",
            ),
        ),
    ]
