# Generated by Django 5.0.9 on 2026-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("herd", "0005_herdmovement_origin_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="herdmovement",
            name="death_cause",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DOENCA", "Doença"),
                    ("PARASITOSE", "Parasitose / verminose"),
                    ("TIMPANISMO", "Timpanismo"),
                    ("INTOXICACAO", "Intoxicação"),
                    ("PICADA_DE_COBRA", "Picada de cobra"),
                    ("ONCA", "Ataque de onça / predador"),
                    ("ACIDENTE", "Acidente"),
                    ("RAIO", "Raio"),
                    ("PARTO", "Problema de parto"),
                    ("OUTRA", "Outra"),
                ],
                help_text="Só em morte, e só se souber. Alimenta o relatório de mortalidade.",
                max_length=20,
                verbose_name="Causa da morte",
            ),
        ),
    ]
