# Generated by Django 5.0.9 on 2026-10-04 05:12

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("herd", "0006_herdmovement_death_cause"),
        ("livestock", "0004_lot_regime"),
        ("organizations", "0003_season_uniq_current_season_per_company"),
        ("partners", "0002_indices_de_desempenho"),
        (
            "properties",
            "0002_farm_business_unit_farm_city_farm_pasture_area_ha_and_more",
        ),
        ("purchases", "0003_purchase_entry_yield_percent_and_more"),
        ("sales", "0003_sale_payment_condition_sale_reported_yield_percent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # `CREATE INDEX CONCURRENTLY` não trava a escrita enquanto o índice é
    # construído (importa em produção, com a tabela em uso). Exige fora de
    # transação.
    atomic = False

    operations = [
        AddIndexConcurrently(
            model_name="herdledgerentry",
            index=models.Index(
                fields=["farm", "date"],
                include=("lot", "quantity"),
                name="herd_ledger_farm_date_inc",
            ),
        ),
        AddIndexConcurrently(
            model_name="herdmovement",
            index=models.Index(fields=["-date", "-id"], name="herd_mov_date_id_desc"),
        ),
        AddIndexConcurrently(
            model_name="herdmovement",
            index=models.Index(fields=["type", "date"], name="herd_mov_type_date"),
        ),
        AddIndexConcurrently(
            model_name="weighing",
            index=models.Index(fields=["lot", "date"], name="weighing_lot_date"),
        ),
    ]
