# Generated by Django 5.0.9 on 2026-10-02 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("livestock", "0003_lot_origin_purchase_alter_lot_status"),
        ("organizations", "0003_season_uniq_current_season_per_company"),
        ("partners", "0001_initial"),
        (
            "properties",
            "0002_farm_business_unit_farm_city_farm_pasture_area_ha_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("CONFIRMADA", "Confirmada"),
                            ("EXCLUIDA", "Excluída"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versão"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "delete_reason",
                    models.TextField(blank=True, verbose_name="Motivo da exclusão"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "type",
                    models.CharField(
                        choices=[("ABATE", "Abate"), ("VENDA", "Venda de animal vivo")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("head_count", models.PositiveIntegerField(verbose_name="Cabeças")),
                (
                    "total_weight_kg",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Peso vivo de saída (kg)",
                    ),
                ),
                (
                    "carcass_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Peso de carcaça (kg)",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor total (R$)"
                    ),
                ),
                (
                    "sale_form",
                    models.CharField(
                        choices=[("PASTO", "Pasto"), ("CONFINAMENTO", "Confinamento")],
                        default="PASTO",
                        max_length=15,
                        verbose_name="Forma",
                    ),
                ),
                (
                    "partnership",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Parceria"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases_from_us",
                        to="partners.partner",
                        verbose_name="Comprador",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="livestock.animalcategory",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Excluído por",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="properties.farm",
                        verbose_name="Fazenda",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="livestock.lot",
                        verbose_name="Lote",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="organizations.season",
                        verbose_name="Safra",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas e abates",
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["farm", "season"], name="sales_sale_farm_id_292acf_idx"
                    ),
                    models.Index(
                        fields=["lot", "status"], name="sales_sale_lot_id_7f073c_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                check=models.Q(("head_count__gt", 0)), name="sale_head_count_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                check=models.Q(("total_weight_kg__gt", 0)),
                name="sale_total_weight_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                check=models.Q(("total_value__gt", 0)), name="sale_total_value_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("carcass_weight_kg__isnull", True),
                    ("carcass_weight_kg__gt", 0),
                    _connector="OR",
                ),
                name="sale_carcass_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("carcass_weight_kg__isnull", True),
                    ("carcass_weight_kg__lt", models.F("total_weight_kg")),
                    _connector="OR",
                ),
                name="sale_carcass_below_live_weight",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("type", "ABATE"),
                    ("carcass_weight_kg__isnull", True),
                    _connector="OR",
                ),
                name="sale_carcass_only_in_abate",
            ),
        ),
    ]
