# Generated by Django 5.0.9 on 2026-10-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="payment_days",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Prazo de recebimento (dias)"
            ),
        ),
    ]
