# Generated by Django 5.0.9 on 2026-10-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_season_no_overlap_trigger'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('company',), name='uniq_current_season_per_company'),
        ),
    ]
