# Generated by Django 5.0.9 on 2026-10-01 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CUSTOS', 'Custos (aba CUSTOS)'), ('COMPRAS', 'Compras de gado (aba COMPRA DE GADO)'), ('MOVIMENTACOES', 'Movimentações das fazendas (abas de fazenda)')], max_length=20, verbose_name='Tipo')),
                ('original_name', models.CharField(max_length=255, verbose_name='Arquivo')),
                ('file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='Arquivo guardado')),
                ('file_hash', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256 do arquivo')),
                ('status', models.CharField(choices=[('PREVIA', 'Em prévia'), ('IMPORTADO', 'Importada'), ('CANCELADO', 'Cancelada')], default='PREVIA', max_length=12, verbose_name='Situação')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='Opções')),
                ('read_stats', models.JSONField(blank=True, default=dict, verbose_name='Leitura')),
                ('duplicate_confirmed', models.BooleanField(default=False, verbose_name='Reimportação confirmada')),
                ('failure_message', models.TextField(blank=True, verbose_name='Motivo da última falha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('finished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Concluída por')),
            ],
            options={
                'verbose_name': 'Importação',
                'verbose_name_plural': 'Importações',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(max_length=60, verbose_name='Aba')),
                ('row_number', models.PositiveIntegerField(verbose_name='Linha')),
                ('raw', models.JSONField(default=dict, verbose_name='Linha crua')),
                ('status', models.CharField(choices=[('VALIDA', 'Pronta'), ('PENDENTE', 'Pendente'), ('ERRO', 'Com erro'), ('IGNORADA', 'Ignorada'), ('IMPORTADA', 'Importada')], db_index=True, default='PENDENTE', max_length=10, verbose_name='Situação')),
                ('messages', models.JSONField(blank=True, default=list, verbose_name='Mensagens')),
                ('resolution', models.JSONField(blank=True, default=dict, verbose_name='Decisão do usuário')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Dados derivados')),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importbatch', verbose_name='Importação')),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Linha importada',
                'verbose_name_plural': 'Linhas importadas',
                'ordering': ['sheet', 'row_number', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'sheet', 'row_number'), name='uniq_importrow_batch_sheet_row'),
        ),
    ]
