# Generated by Django 5.0.9 on 2026-10-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CUSTOS", "Custos (aba CUSTOS)"),
                    ("COMPRAS", "Compras de gado (aba COMPRA DE GADO)"),
                    ("MOVIMENTACOES", "Movimentações das fazendas (abas de fazenda)"),
                    ("VENDAS", "Vendas e abates (aba VENDAS)"),
                    ("PESAGENS", "Pesagens (aba PESAGENS E CONFERENCIA)"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
